### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by 57ar7up** [KoltesDigital/atom-foxdot#1]
Steps to reproduce: Run code

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Windows 10 x64
**Thrown From**: [foxdot](https://github.com/KoltesDigital/atom-foxdot) package 1.0.0

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:183

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Object.evaluateCode (/packages/foxdot/lib/foxdot.js:112:9)
    at Object.evaluateRange (/packages/foxdot/lib/foxdot.js:130:8)
    at /packages/foxdot/lib/foxdot.js:134:39
    at Array.forEach (<anonymous>)
    at Object.evaluateRanges (/packages/foxdot/lib/foxdot.js:134:17)
    at Object.evaluateBlocks (/packages/foxdot/lib/foxdot.js:176:15)
    at HTMLElement.foxdotEvaluateBlocks (/packages/foxdot/lib/foxdot.js:39:10)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.2/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.2/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -7:37.2.0 core:paste (input.hidden-input)
  6x -7:29.2.0 core:backspace (input.hidden-input)
  2x -7:26.8.0 core:undo (input.hidden-input)
 15x -7:13.1.0 intentions:highlight (input.hidden-input)
     -7:11.8.0 foxdot:toggle (input.hidden-input)
     -6:43.1.0 core:save (div.package-detail.panels-item)
     -6:35.6.0 intentions:highlight (input.hidden-input)
     -6:34.4.0 foxdot:toggle (input.hidden-input)
     -6:12.6.0 intentions:highlight (input.hidden-input)
     -6:11.7.0 foxdot:toggle (input.hidden-input)
     -5:23.1.0 intentions:highlight (input.hidden-input)
     -5:22.6.0 foxdot:toggle (input.hidden-input)
     -5:17 intentions:highlight (input.hidden-input)
     -5:16.1.0 foxdot:toggle (input.hidden-input)
     -5:10.6.0 intentions:highlight (input.hidden-input)
     -5:10.3.0 foxdot:evaluate-blocks (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-bracket-highlight 0.3.2 
atom-ide-ui 0.12.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.5 
color-picker 2.3.0 
convert-to-utf8 0.2.4 
file-icons 2.1.22 
foxdot 1.0.0 
ghost-text 0.0.1 
highlight-selected 0.14.0 
Hydrogen 2.5.1 
intentions 1.1.5 
language-autohotkey2 1.0.1 
language-lua 0.9.11 
language-matlab 0.2.1 
language-prototxt 0.0.1 
language-pug 0.0.22 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jshint 3.1.8 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pigments 0.40.2 
tree-view-autoresize 2.3.0 
```

**Comment by KoltesDigital** [comment]
I don't understand how, here's a quick patch that might fix it.

**Comment by 57ar7up** [comment]
Thanks. error is no longer there, and all works!
