### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by AKattorC** [KoltesDigital/atom-foxdot#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [foxdot](https://github.com/KoltesDigital/atom-foxdot) package 1.0.0

### Stack Trace

Uncaught Error: This socket is closed

```
At events.js:183

Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Object.evaluateCode (/packages/foxdot/lib/foxdot.js:112:9)
    at Object.evaluateRange (/packages/foxdot/lib/foxdot.js:130:8)
    at Object.evaluateFile (/packages/foxdot/lib/foxdot.js:144:15)
    at HTMLElement.foxdotEvaluateFile (/packages/foxdot/lib/foxdot.js:45:10)
    at CommandRegistry.handleCommandEvent (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at CommandRegistry.dispatch (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:348530)
    at AtomEnvironment.dispatchContextMenuCommand (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:1:694360)
    at EventEmitter.t (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:1:701827)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:15.4.0 foxdot:toggle (div.highlights)
     -0:01.9.0 foxdot:evaluate-file (div.highlights)
```

### Non-Core Packages

```
foxdot 1.0.0 
```

**Comment by KoltesDigital** [comment]
This is supposed to be resolved in foxdot 1.0.1. Has not atom proposed to update the package?
