### ISSUE TITLE
Uncaught Error: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by iTerentius** [KoltesDigital/atom-foxdot#9]
Evaluating starter code:
p1 >> pluck()

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04
**Thrown From**: [foxdot](https://github.com/KoltesDigital/atom-foxdot) package 1.1.0

### Stack Trace

Uncaught Error: Cannot call write after a stream was destroyed

```
At events.js:171

Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at FoxDot.evaluateCode (/packages/foxdot/lib/foxdot.js:77:15)
    at FoxDot.evaluateRange (/packages/foxdot/lib/foxdot.js:117:14)
    at FoxDot.evaluateFile (/packages/foxdot/lib/foxdot.js:87:21)
    at /packages/foxdot/lib/index.js:95:24)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349786)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348261)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:725973)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:733896)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
  5x -1:27.5.0 core:backspace (input.hidden-input)
     -0:37 core:paste (input.hidden-input)
     -0:30.3.0 foxdot:evaluate-file (input.hidden-input)
```

### Non-Core Packages

```
foxdot 1.1.0 
```

**Comment by laelume** [comment]
What version of SuperCollider are you using?

**Comment by KoltesDigital** [comment]
Sorry for not catching up. Do you still have the issue?
